import { ItemCode } from '@/plugins/utils/enums';

const cdnURL = `https://cdn.tkfmdata.com`

function getItemIconPath(id: string): string{
    return `${cdnURL}/item/${id}.png`
}

export const Icon = {
    [ItemCode.SLIVER_COIN]: getItemIconPath('IP00001'),
    [ItemCode.NAMELESS]: getItemIconPath('IP28002'),
    [ItemCode.FLAWLESS]: getItemIconPath('IP31501'),
    [ItemCode.SKILL_FRAGMENT]: getItemIconPath('IP31901'),
    [ItemCode.SKILL_STONE]: getItemIconPath('IP31902'),
    [ItemCode.LIBERATE_STONE]: getItemIconPath('IP31903'),
    [ItemCode.EVOLVE_FIRE_LV1]: getItemIconPath('IP31001'),
    [ItemCode.EVOLVE_FIRE_LV2]: getItemIconPath('IP31002'),
    [ItemCode.EVOLVE_FIRE_LV3]: getItemIconPath('IP31003'),
    [ItemCode.EVOLVE_FIRE_LV4]: getItemIconPath('IP31004'),
    [ItemCode.EVOLVE_WATER_LV1]: getItemIconPath('IP31011'),
    [ItemCode.EVOLVE_WATER_LV2]: getItemIconPath('IP31012'),
    [ItemCode.EVOLVE_WATER_LV3]: getItemIconPath('IP31013'),
    [ItemCode.EVOLVE_WATER_LV4]: getItemIconPath('IP31014'),
    [ItemCode.EVOLVE_WIND_LV1]: getItemIconPath('IP31021'),
    [ItemCode.EVOLVE_WIND_LV2]: getItemIconPath('IP31022'),
    [ItemCode.EVOLVE_WIND_LV3]: getItemIconPath('IP31023'),
    [ItemCode.EVOLVE_WIND_LV4]: getItemIconPath('IP31024'),
    [ItemCode.EVOLVE_LIGHT_LV1]: getItemIconPath('IP31031'),
    [ItemCode.EVOLVE_LIGHT_LV2]: getItemIconPath('IP31032'),
    [ItemCode.EVOLVE_LIGHT_LV3]: getItemIconPath('IP31033'),
    [ItemCode.EVOLVE_LIGHT_LV4]: getItemIconPath('IP31034'),
    [ItemCode.EVOLVE_DARK_LV1]: getItemIconPath('IP31041'),
    [ItemCode.EVOLVE_DARK_LV2]: getItemIconPath('IP31042'),
    [ItemCode.EVOLVE_DARK_LV3]: getItemIconPath('IP31043'),
    [ItemCode.EVOLVE_DARK_LV4]: getItemIconPath('IP31044'),
    [ItemCode.CLAW_LV1]: getItemIconPath('IP30001'),
    [ItemCode.CLAW_LV2]: getItemIconPath('IP30002'),
    [ItemCode.CLAW_LV3]: getItemIconPath('IP30003'),
    [ItemCode.IRON_LV1]: getItemIconPath('IP30004'),
    [ItemCode.IRON_LV2]: getItemIconPath('IP30005'),
    [ItemCode.IRON_LV3]: getItemIconPath('IP30006'),
    [ItemCode.WATER_LV1]: getItemIconPath('IP30007'),
    [ItemCode.WATER_LV2]: getItemIconPath('IP30008'),
    [ItemCode.WATER_LV3]: getItemIconPath('IP30009'),
    [ItemCode.MIXTURE_LV1]: getItemIconPath('IP30010'),
    [ItemCode.MIXTURE_LV2]: getItemIconPath('IP30011'),
    [ItemCode.MIXTURE_LV3]: getItemIconPath('IP30012'),
    [ItemCode.DUST_LV1]: getItemIconPath('IP30013'),
    [ItemCode.DUST_LV2]: getItemIconPath('IP30014'),
    [ItemCode.DUST_LV3]: getItemIconPath('IP30015'),
    [ItemCode.HORN_LV1]: getItemIconPath('IP30016'),
    [ItemCode.HORN_LV2]: getItemIconPath('IP30017'),
    [ItemCode.SLIVER_LV1]: getItemIconPath('IP30018'),
    [ItemCode.SLIVER_LV2]: getItemIconPath('IP30019'),
    [ItemCode.OIL_LV1]: getItemIconPath('IP30020'),
    [ItemCode.OIL_LV2]: getItemIconPath('IP30021'),
    [ItemCode.CRYSTAL_LV1]: getItemIconPath('IP30022'),
    [ItemCode.CRYSTAL_LV2]: getItemIconPath('IP30023'),
    [ItemCode.FANG_LV1]: getItemIconPath('IP30024'),
    [ItemCode.FANG_LV2]: getItemIconPath('IP30025'),
    [ItemCode.BEAK_LV1]: getItemIconPath('IP30026'),
    [ItemCode.BEAK_LV2]: getItemIconPath('IP30027'),
    [ItemCode.SKIN_LV1]: getItemIconPath('IP30028'),
    [ItemCode.SKIN_LV2]: getItemIconPath('IP30029'),
    [ItemCode.BOOK_LV1]: getItemIconPath('IP30030'),
    [ItemCode.BOOK_LV2]: getItemIconPath('IP30031'),
    [ItemCode.FEATHER_LV1]: getItemIconPath('IP30032'),
    [ItemCode.FEATHER_LV2]: getItemIconPath('IP30033'),
    [ItemCode.WEB_LV1]: getItemIconPath('IP30034'),
    [ItemCode.WEB_LV2]: getItemIconPath('IP30035'),
    [ItemCode.DISCIPLINE_FIRE_LV1]: getItemIconPath('IP35101'),
    [ItemCode.DISCIPLINE_FIRE_LV2]: getItemIconPath('IP35204'),
    [ItemCode.DISCIPLINE_FIRE_LV3]: getItemIconPath('IP35302'),
    [ItemCode.DISCIPLINE_WATER_LV1]: getItemIconPath('IP35105'),
    [ItemCode.DISCIPLINE_WATER_LV2]: getItemIconPath('IP35201'),
    [ItemCode.DISCIPLINE_WATER_LV3]: getItemIconPath('IP35305'),
    [ItemCode.DISCIPLINE_WIND_LV1]: getItemIconPath('IP35103'),
    [ItemCode.DISCIPLINE_WIND_LV2]: getItemIconPath('IP35203'),
    [ItemCode.DISCIPLINE_WIND_LV3]: getItemIconPath('IP35301'),
    [ItemCode.DISCIPLINE_LIGHT_LV1]: getItemIconPath('IP35104'),
    [ItemCode.DISCIPLINE_LIGHT_LV2]: getItemIconPath('IP35202'),
    [ItemCode.DISCIPLINE_LIGHT_LV3]: getItemIconPath('IP35303'),
    [ItemCode.DISCIPLINE_DARK_LV1]: getItemIconPath('IP35102'),
    [ItemCode.DISCIPLINE_DARK_LV2]: getItemIconPath('IP35205'),
    [ItemCode.DISCIPLINE_DARK_LV3]: getItemIconPath('IP35304'),
    [ItemCode.DISCIPLINE_FRUIT]: getItemIconPath('IP35403'),
    [ItemCode.EXP_LV1]: getItemIconPath('IP21001'),
    [ItemCode.EXP_LV2]: getItemIconPath('IP21002'),
    [ItemCode.EXP_LV3]: getItemIconPath('IP21003'),
    [ItemCode.EXP_LV4]: getItemIconPath('IP21004'),
}