import { UnitCode } from '@/plugins/utils/enums';

const cdnURL = `https://cdn.tkfmdata.com`

function getUnitEssencePath(id: string): string{
    return `${cdnURL}/character/essence/IP${id}.png`;
}

const N = {
    [UnitCode.saria]: getUnitEssencePath('10901'),
    [UnitCode.petra]: getUnitEssencePath('10902'),
    [UnitCode.flay]: getUnitEssencePath('10903'),
    [UnitCode.manuella]: getUnitEssencePath('10904'),
    [UnitCode.kikyou]: getUnitEssencePath('10905'),
    [UnitCode.kaede]: getUnitEssencePath('10906'),
    [UnitCode.ola]: getUnitEssencePath('10907'),
    [UnitCode.kani]: getUnitEssencePath('10908'),
    [UnitCode.charlene]: getUnitEssencePath('10909'),
    [UnitCode.martina]: getUnitEssencePath('10910'),
    [UnitCode.clarie]: getUnitEssencePath('10911'),
    [UnitCode.lori]: getUnitEssencePath('10912'),
    [UnitCode.minnow]: getUnitEssencePath('10913'),
    [UnitCode.lamia]: getUnitEssencePath('10914'),
    [UnitCode.harpy]: getUnitEssencePath('10915'),
    [UnitCode.anna]: getUnitEssencePath('10916'),
    [UnitCode.blaire]: getUnitEssencePath('10917'),
    [UnitCode.natasha]: getUnitEssencePath('10918'),
    [UnitCode.prototype]: getUnitEssencePath('10922'),
    [UnitCode.punishment]: getUnitEssencePath('10919'),
    [UnitCode.bliss]: getUnitEssencePath('10920'),
    [UnitCode.mareyl]: getUnitEssencePath('10923'),
    [UnitCode.mumu]: getUnitEssencePath('10924'),
    [UnitCode.molly]: getUnitEssencePath('10921'),
    [UnitCode.anya]: getUnitEssencePath('10933'),
}

const R = {
    [UnitCode.irene]: getUnitEssencePath('10801'),
    [UnitCode.nana]: getUnitEssencePath('10802'),
    [UnitCode.iris]: getUnitEssencePath('10803'),
    [UnitCode.dora]: getUnitEssencePath('10804'),
    [UnitCode.sable]: getUnitEssencePath('10805'),
    [UnitCode.marlene]: getUnitEssencePath('10806'),
    [UnitCode.yoi]: getUnitEssencePath('10807'),
    [UnitCode.shiraka]: getUnitEssencePath('10808'),
    [UnitCode.panana]: getUnitEssencePath('10812'),
    [UnitCode.sophie]: getUnitEssencePath('10810'),
    [UnitCode.jolina]: getUnitEssencePath('10811'),
    [UnitCode.mia]: getUnitEssencePath('10809'),
    [UnitCode.iyan]: getUnitEssencePath('10813'),
}

const SR = {
    [UnitCode.aiko]: getUnitEssencePath('10009'),
    [UnitCode.leona]: getUnitEssencePath('10010'),
    [UnitCode.fiora]: getUnitEssencePath('10011'),
    [UnitCode.ritsuki]: getUnitEssencePath('10012'),
    [UnitCode.minayomi]: getUnitEssencePath('10013'),
    [UnitCode.shizuka]: getUnitEssencePath('10014'),
    [UnitCode.juneau]: getUnitEssencePath('10015'),
    [UnitCode.britney]: getUnitEssencePath('10016'),
    [UnitCode.nafrala]: getUnitEssencePath('10036'),
    [UnitCode.tyrella]: getUnitEssencePath('10038'),
    [UnitCode.teresa]: getUnitEssencePath('10061'),
    [UnitCode.pulicia]: getUnitEssencePath('10051'),
    [UnitCode.janelle]: getUnitEssencePath('10046'),
    [UnitCode.tanocia]: getUnitEssencePath('10055'),
    [UnitCode.yingying]: getUnitEssencePath('10041'),
}

const SSR = {
    [UnitCode.baal]: getUnitEssencePath('10001'),
    [UnitCode.satan]: getUnitEssencePath('10002'),
    [UnitCode.iblis]: getUnitEssencePath('10003'),
    [UnitCode.salucia]: getUnitEssencePath('10004'),
    [UnitCode.lana]: getUnitEssencePath('10005'),
    [UnitCode.lulu]: getUnitEssencePath('10006'),
    [UnitCode.f_baal]: getUnitEssencePath('10017'),
    [UnitCode.i_iblis]: getUnitEssencePath('10025'),
    [UnitCode.noel]: getUnitEssencePath('10026'),
    [UnitCode.ks8]: getUnitEssencePath('10008'),
    [UnitCode.mesmiia]: getUnitEssencePath('10037'),
    [UnitCode.e_satan]: getUnitEssencePath('10027'),
    [UnitCode.chizuru]: getUnitEssencePath('10028'),
    [UnitCode.daphne]: getUnitEssencePath('10057'),
    [UnitCode.s_shizuka]: getUnitEssencePath('10029'),
    [UnitCode.s_lulu]: getUnitEssencePath('10030'),
    [UnitCode.s_ks8]: getUnitEssencePath('10031'),
    [UnitCode.s_nana]: getUnitEssencePath('10032'),
    [UnitCode.milae]: getUnitEssencePath('10007'),
    [UnitCode.asida]: getUnitEssencePath('10034'),
    [UnitCode.asina]: getUnitEssencePath('10035'),
    [UnitCode.aridya]: getUnitEssencePath('10033'),
    [UnitCode.lotiya]: getUnitEssencePath('10039'),
    [UnitCode.fufu]: getUnitEssencePath('10058'),
    [UnitCode.hm_fiora]: getUnitEssencePath('10060'),
    [UnitCode.karina]: getUnitEssencePath('10056'),
    [UnitCode.ibuki]: getUnitEssencePath('10045'),
    [UnitCode.h_britney]: getUnitEssencePath('10040'),
    [UnitCode.h_salucia]: getUnitEssencePath('10043'),
    [UnitCode.inori]: getUnitEssencePath('10059'),
    [UnitCode.sakuya]: getUnitEssencePath('10083'),
    [UnitCode.x_aiko]: getUnitEssencePath('10052'),
    [UnitCode.x_lana]: getUnitEssencePath('10053'),
    [UnitCode.evie]: getUnitEssencePath('10054'),
    [UnitCode.tm_minayomi]: getUnitEssencePath('10067'),
    [UnitCode.tm_ritsuki]: getUnitEssencePath('10079'),
    [UnitCode.b_baal]: getUnitEssencePath('10072'),
    [UnitCode.b_iblis]: getUnitEssencePath('10081'),
    [UnitCode.b_satan]: getUnitEssencePath('10082'),
    [UnitCode.miru]: getUnitEssencePath('10084'),
    [UnitCode.uruta]: getUnitEssencePath('10018'),
    [UnitCode.ayane]: getUnitEssencePath('10019'),
    [UnitCode.muila]: getUnitEssencePath('10020'),
    [UnitCode.f_caesar]: getUnitEssencePath('10050'),
    [UnitCode.w_chizuru]: getUnitEssencePath('10075'),
    [UnitCode.w_lulu]: getUnitEssencePath('10076'),
    [UnitCode.faya]: getUnitEssencePath('10049'),
    [UnitCode.usagihime]: getUnitEssencePath('10100'),
    [UnitCode.s_iblis]: getUnitEssencePath('10042'),
    [UnitCode.s_milae]: getUnitEssencePath('10090'),
    [UnitCode.s_noel]: getUnitEssencePath('10091'),
    [UnitCode.s_aridya]: getUnitEssencePath('10092'),
    [UnitCode.ichika]: getUnitEssencePath('10074'),
    [UnitCode.kana]: getUnitEssencePath('10085'),
    [UnitCode.q_asida]: getUnitEssencePath('10088'),
    [UnitCode.q_asina]: getUnitEssencePath('10089'),
    [UnitCode.emily]: getUnitEssencePath('10063'),
    [UnitCode.anjelica]: getUnitEssencePath('10066'),
    [UnitCode.c1_nana]: getUnitEssencePath('10093'),
    [UnitCode.geneva]: getUnitEssencePath('10094'),
    [UnitCode.lotus]: getUnitEssencePath('10068'),
    [UnitCode.didi]: getUnitEssencePath('10047'),
    [UnitCode.h_leona]: getUnitEssencePath('10095'),
    [UnitCode.h_lotiya]: getUnitEssencePath('10096'),
    [UnitCode.sherana]: getUnitEssencePath('10062'),
    [UnitCode.elizabeth]: getUnitEssencePath('10024'),
    [UnitCode.xx_aiko]: getUnitEssencePath('10097'),
    [UnitCode.x_shizuka]: getUnitEssencePath('10098'),
    [UnitCode.shiro]: getUnitEssencePath('10021'),
    [UnitCode.ny_salucia]: getUnitEssencePath('10106'),
    [UnitCode.ny_lana]: getUnitEssencePath('10107'),
    [UnitCode.v_baal]: getUnitEssencePath('10108'),
    [UnitCode.v_iblis]: getUnitEssencePath('10109'),
    [UnitCode.v_satan]: getUnitEssencePath('10110'),
    [UnitCode.lillane]: getUnitEssencePath('10069'),
    [UnitCode.c_lulu]: getUnitEssencePath('10078'),
    [UnitCode.m_juneau]: getUnitEssencePath('10114'),
    [UnitCode.m_britney]: getUnitEssencePath('10115'),
    [UnitCode.momo]: getUnitEssencePath('10048'),
    [UnitCode.n_caesar]: getUnitEssencePath('10113'),
    [UnitCode.d_irene]: getUnitEssencePath('10111'),
    [UnitCode.s_ayane]: getUnitEssencePath('10116'),
    [UnitCode.s_baal]: getUnitEssencePath('10117'),
    [UnitCode.s_fiora]: getUnitEssencePath('10118'),
    [UnitCode.s_aiko]: getUnitEssencePath('10119'),
    [UnitCode.o_lana]: getUnitEssencePath('10120'),
    [UnitCode.o_nana]: getUnitEssencePath('10121'),
    [UnitCode.sasha]: getUnitEssencePath('10071'),
    [UnitCode.bayliss]: getUnitEssencePath('10077'),
    [UnitCode.a_usagihime]: getUnitEssencePath('10122'),
    [UnitCode.d_miru]: getUnitEssencePath('10123'),
    [UnitCode.nyoro]: getUnitEssencePath('10124'),
    [UnitCode.h_ayane]: getUnitEssencePath('10125'),
    [UnitCode.h_shiro]: getUnitEssencePath('10126'),
    [UnitCode.inase]: getUnitEssencePath('10131'),
    [UnitCode.cartilla]: getUnitEssencePath('10132'),
    [UnitCode.x_aridya]: getUnitEssencePath('10127'),
    [UnitCode.x_iblis]: getUnitEssencePath('10128'),
    [UnitCode.w_evie]: getUnitEssencePath('10129'),
    [UnitCode.salina]: getUnitEssencePath('10130'),
    [UnitCode.noma]: getUnitEssencePath('10022'),
    [UnitCode.belladonna]: getUnitEssencePath('10023'),
    [UnitCode.nanami]: getUnitEssencePath('10133'),
    [UnitCode.w_noel]: getUnitEssencePath('10134'),
    [UnitCode.w_mesmiia]: getUnitEssencePath('10135'),
    [UnitCode.angelina]: getUnitEssencePath('10136'),
    [UnitCode.w_lillane]: getUnitEssencePath('10137'),
    [UnitCode.p_lulu]: getUnitEssencePath('10138'),
    [UnitCode.p_tyrella]: getUnitEssencePath('10139'),
    [UnitCode.lelya]: getUnitEssencePath('10140'),
    [UnitCode.a_nana]: getUnitEssencePath('10141'),
    [UnitCode.s_chizuru]: getUnitEssencePath('10142'),
    [UnitCode.s_salucia]: getUnitEssencePath('10143'),
    [UnitCode.s_caesar]: getUnitEssencePath('10144'),
    [UnitCode.s_satan]: getUnitEssencePath('10145'),
    [UnitCode.d_minayomi]: getUnitEssencePath('10146'),
    [UnitCode.oniyoiki]: getUnitEssencePath('10147'),
    [UnitCode.beer_shizuka]: getUnitEssencePath('10148'),
    [UnitCode.tsubaki]: getUnitEssencePath('10149'),
    [UnitCode.amethystina]: getUnitEssencePath('10044'),
    [UnitCode.bg_ayane]: getUnitEssencePath('10150'),
    [UnitCode.bg_iblis]: getUnitEssencePath('10151'),
    [UnitCode.susan]: getUnitEssencePath('10152'),
    [UnitCode.h_satan]: getUnitEssencePath('10153'),
    [UnitCode.m_nanami]: getUnitEssencePath('10154'),
    [UnitCode.m_ks8]: getUnitEssencePath('10155'),
    [UnitCode.x_baal]: getUnitEssencePath('10156'),
    [UnitCode.x_muila]: getUnitEssencePath('10157'),
    [UnitCode.x_britney]: getUnitEssencePath('10158'),
    [UnitCode.x_ichika]: getUnitEssencePath('10175'),
    [UnitCode.ny_fiora]: getUnitEssencePath('10159'),
    [UnitCode.zaskia]: getUnitEssencePath('10161'),
    [UnitCode.p_aiko]: getUnitEssencePath('10162'),
    [UnitCode.ni_caesar]: getUnitEssencePath('10163'),
    [UnitCode.f_kana]: getUnitEssencePath('10164'),
    [UnitCode.star_mia]: getUnitEssencePath('10165'),
    [UnitCode.star_annee]: getUnitEssencePath('10166'),
    [UnitCode.bedard]: getUnitEssencePath('10176'),
    [UnitCode.c_noel]: getUnitEssencePath('10167'),
    [UnitCode.eunice]: getUnitEssencePath('10168'),
    [UnitCode.momDaphne]: getUnitEssencePath('10169'),
    [UnitCode.w_tsubaki]: getUnitEssencePath('10170'),
    [UnitCode.ss_iblis]: getUnitEssencePath('10171'),
    [UnitCode.s_evie]: getUnitEssencePath('10172'),
    [UnitCode.s_noma]: getUnitEssencePath('10173'),
    [UnitCode.forneusa]: getUnitEssencePath('10174'),
    [UnitCode.bu_ayane]: getUnitEssencePath('10160'),
    [UnitCode.sky_nanami]: getUnitEssencePath('10177'),
    [UnitCode.sky_baal]: getUnitEssencePath('10178'),
}

export const Essence = {
    ...N,
    ...R,
    ...SR,
    ...SSR
}