import { UnitCode } from '@/plugins/utils/enums';

const cdnURL = `https://cdn.tkfmdata.com`

function getUnitFullImagePath(id: string): string[][]{
    var result: string[][] = []
    for (let i = 1; i <= 3; i++) {
        result.push([])
        for (let j = 0; j < 3 ; j++) {
            result[i-1].push(`${cdnURL}/character/fullbody/${id}_${j}-Lv${i}.png`);
        }
    }
    return result;
}

const N = {
    [UnitCode.saria]: getUnitFullImagePath('10901'),
    [UnitCode.petra]: getUnitFullImagePath('10902'),
    [UnitCode.flay]: getUnitFullImagePath('10903'),
    [UnitCode.manuella]: getUnitFullImagePath('10904'),
    [UnitCode.kikyou]: getUnitFullImagePath('10905'),
    [UnitCode.kaede]: getUnitFullImagePath('10906'),
    [UnitCode.ola]: getUnitFullImagePath('10907'),
    [UnitCode.kani]: getUnitFullImagePath('10908'),
    [UnitCode.charlene]: getUnitFullImagePath('10909'),
    [UnitCode.martina]: getUnitFullImagePath('10910'),
    [UnitCode.clarie]: getUnitFullImagePath('10911'),
    [UnitCode.lori]: getUnitFullImagePath('10912'),
    [UnitCode.minnow]: getUnitFullImagePath('10913'),
    [UnitCode.lamia]: getUnitFullImagePath('10914'),
    [UnitCode.harpy]: getUnitFullImagePath('10915'),
    [UnitCode.anna]: getUnitFullImagePath('10916'),
    [UnitCode.blaire]: getUnitFullImagePath('10917'),
    [UnitCode.natasha]: getUnitFullImagePath('10918'),
    [UnitCode.prototype]: getUnitFullImagePath('10922'),
    [UnitCode.punishment]: getUnitFullImagePath('10919'),
    [UnitCode.bliss]: getUnitFullImagePath('10920'),
    [UnitCode.mareyl]: getUnitFullImagePath('10923'),
    [UnitCode.mumu]: getUnitFullImagePath('10924'),
    [UnitCode.molly]: getUnitFullImagePath('10921'),
    [UnitCode.anya]: getUnitFullImagePath('10933'),
}

const R = {
    [UnitCode.irene]: getUnitFullImagePath('10801'),
    [UnitCode.nana]: getUnitFullImagePath('10802'),
    [UnitCode.iris]: getUnitFullImagePath('10803'),
    [UnitCode.dora]: getUnitFullImagePath('10804'),
    [UnitCode.sable]: getUnitFullImagePath('10805'),
    [UnitCode.marlene]: getUnitFullImagePath('10806'),
    [UnitCode.yoi]: getUnitFullImagePath('10807'),
    [UnitCode.shiraka]: getUnitFullImagePath('10808'),
    [UnitCode.panana]: getUnitFullImagePath('10812'),
    [UnitCode.sophie]: getUnitFullImagePath('10810'),
    [UnitCode.jolina]: getUnitFullImagePath('10811'),
    [UnitCode.mia]: getUnitFullImagePath('10809'),
    [UnitCode.iyan]: getUnitFullImagePath('10813'),
}

const SR = {
    [UnitCode.aiko]: getUnitFullImagePath('10009'),
    [UnitCode.leona]: getUnitFullImagePath('10010'),
    [UnitCode.fiora]: getUnitFullImagePath('10011'),
    [UnitCode.ritsuki]: getUnitFullImagePath('10012'),
    [UnitCode.minayomi]: getUnitFullImagePath('10013'),
    [UnitCode.shizuka]: getUnitFullImagePath('10014'),
    [UnitCode.juneau]: getUnitFullImagePath('10015'),
    [UnitCode.britney]: getUnitFullImagePath('10016'),
    [UnitCode.nafrala]: getUnitFullImagePath('10036'),
    [UnitCode.tyrella]: getUnitFullImagePath('10038'),
    [UnitCode.teresa]: getUnitFullImagePath('10061'),
    [UnitCode.pulicia]: getUnitFullImagePath('10051'),
    [UnitCode.janelle]: getUnitFullImagePath('10046'),
    [UnitCode.tanocia]: getUnitFullImagePath('10055'),
    [UnitCode.yingying]: getUnitFullImagePath('10041'),
}

const SSR = {
    [UnitCode.baal]: getUnitFullImagePath('10001'),
    [UnitCode.satan]: getUnitFullImagePath('10002'),
    [UnitCode.iblis]: getUnitFullImagePath('10003'),
    [UnitCode.salucia]: getUnitFullImagePath('10004'),
    [UnitCode.lana]: getUnitFullImagePath('10005'),
    [UnitCode.lulu]: getUnitFullImagePath('10006'),
    [UnitCode.f_baal]: getUnitFullImagePath('10017'),
    [UnitCode.i_iblis]: getUnitFullImagePath('10025'),
    [UnitCode.noel]: getUnitFullImagePath('10026'),
    [UnitCode.ks8]: getUnitFullImagePath('10008'),
    [UnitCode.mesmiia]: getUnitFullImagePath('10037'),
    [UnitCode.e_satan]: getUnitFullImagePath('10027'),
    [UnitCode.chizuru]: getUnitFullImagePath('10028'),
    [UnitCode.daphne]: getUnitFullImagePath('10057'),
    [UnitCode.s_shizuka]: getUnitFullImagePath('10029'),
    [UnitCode.s_lulu]: getUnitFullImagePath('10030'),
    [UnitCode.s_ks8]: getUnitFullImagePath('10031'),
    [UnitCode.s_nana]: getUnitFullImagePath('10032'),
    [UnitCode.milae]: getUnitFullImagePath('10007'),
    [UnitCode.asida]: getUnitFullImagePath('10034'),
    [UnitCode.asina]: getUnitFullImagePath('10035'),
    [UnitCode.aridya]: getUnitFullImagePath('10033'),
    [UnitCode.lotiya]: getUnitFullImagePath('10039'),
    [UnitCode.fufu]: getUnitFullImagePath('10058'),
    [UnitCode.hm_fiora]: getUnitFullImagePath('10060'),
    [UnitCode.karina]: getUnitFullImagePath('10056'),
    [UnitCode.ibuki]: getUnitFullImagePath('10045'),
    [UnitCode.h_britney]: getUnitFullImagePath('10040'),
    [UnitCode.h_salucia]: getUnitFullImagePath('10043'),
    [UnitCode.inori]: getUnitFullImagePath('10059'),
    [UnitCode.sakuya]: getUnitFullImagePath('10083'),
    [UnitCode.x_aiko]: getUnitFullImagePath('10052'),
    [UnitCode.x_lana]: getUnitFullImagePath('10053'),
    [UnitCode.evie]: getUnitFullImagePath('10054'),
    [UnitCode.tm_minayomi]: getUnitFullImagePath('10067'),
    [UnitCode.tm_ritsuki]: getUnitFullImagePath('10079'),
    [UnitCode.b_baal]: getUnitFullImagePath('10072'),
    [UnitCode.b_iblis]: getUnitFullImagePath('10081'),
    [UnitCode.b_satan]: getUnitFullImagePath('10082'),
    [UnitCode.miru]: getUnitFullImagePath('10084'),
    [UnitCode.uruta]: getUnitFullImagePath('10018'),
    [UnitCode.ayane]: getUnitFullImagePath('10019'),
    [UnitCode.muila]: getUnitFullImagePath('10020'),
    [UnitCode.f_caesar]: getUnitFullImagePath('10050'),
    [UnitCode.w_chizuru]: getUnitFullImagePath('10075'),
    [UnitCode.w_lulu]: getUnitFullImagePath('10076'),
    [UnitCode.faya]: getUnitFullImagePath('10049'),
    [UnitCode.usagihime]: getUnitFullImagePath('10100'),
    [UnitCode.s_iblis]: getUnitFullImagePath('10042'),
    [UnitCode.s_milae]: getUnitFullImagePath('10090'),
    [UnitCode.s_noel]: getUnitFullImagePath('10091'),
    [UnitCode.s_aridya]: getUnitFullImagePath('10092'),
    [UnitCode.ichika]: getUnitFullImagePath('10074'),
    [UnitCode.kana]: getUnitFullImagePath('10085'),
    [UnitCode.q_asida]: getUnitFullImagePath('10088'),
    [UnitCode.q_asina]: getUnitFullImagePath('10089'),
    [UnitCode.emily]: getUnitFullImagePath('10063'),
    [UnitCode.anjelica]: getUnitFullImagePath('10066'),
    [UnitCode.c1_nana]: getUnitFullImagePath('10093'),
    [UnitCode.geneva]: getUnitFullImagePath('10094'),
    [UnitCode.lotus]: getUnitFullImagePath('10068'),
    [UnitCode.didi]: getUnitFullImagePath('10047'),
    [UnitCode.h_leona]: getUnitFullImagePath('10095'),
    [UnitCode.h_lotiya]: getUnitFullImagePath('10096'),
    [UnitCode.sherana]: getUnitFullImagePath('10062'),
    [UnitCode.elizabeth]: getUnitFullImagePath('10024'),
    [UnitCode.xx_aiko]: getUnitFullImagePath('10097'),
    [UnitCode.x_shizuka]: getUnitFullImagePath('10098'),
    [UnitCode.shiro]: getUnitFullImagePath('10021'),
    [UnitCode.ny_salucia]: getUnitFullImagePath('10106'),
    [UnitCode.ny_lana]: getUnitFullImagePath('10107'),
    [UnitCode.v_baal]: getUnitFullImagePath('10108'),
    [UnitCode.v_iblis]: getUnitFullImagePath('10109'),
    [UnitCode.v_satan]: getUnitFullImagePath('10110'),
    [UnitCode.lillane]: getUnitFullImagePath('10069'),
    [UnitCode.c_lulu]: getUnitFullImagePath('10078'),
    [UnitCode.m_juneau]: getUnitFullImagePath('10114'),
    [UnitCode.m_britney]: getUnitFullImagePath('10115'),
    [UnitCode.momo]: getUnitFullImagePath('10048'),
    [UnitCode.n_caesar]: getUnitFullImagePath('10113'),
    [UnitCode.d_irene]: getUnitFullImagePath('10111'),
    [UnitCode.s_ayane]: getUnitFullImagePath('10116'),
    [UnitCode.s_baal]: getUnitFullImagePath('10117'),
    [UnitCode.s_fiora]: getUnitFullImagePath('10118'),
    [UnitCode.s_aiko]: getUnitFullImagePath('10119'),
    [UnitCode.o_lana]: getUnitFullImagePath('10120'),
    [UnitCode.o_nana]: getUnitFullImagePath('10121'),
    [UnitCode.sasha]: getUnitFullImagePath('10071'),
    [UnitCode.bayliss]: getUnitFullImagePath('10077'),
    [UnitCode.a_usagihime]: getUnitFullImagePath('10122'),
    [UnitCode.d_miru]: getUnitFullImagePath('10123'),
    [UnitCode.nyoro]: getUnitFullImagePath('10124'),
    [UnitCode.h_ayane]: getUnitFullImagePath('10125'),
    [UnitCode.h_shiro]: getUnitFullImagePath('10126'),
    [UnitCode.inase]: getUnitFullImagePath('10131'),
    [UnitCode.cartilla]: getUnitFullImagePath('10132'),
    [UnitCode.x_aridya]: getUnitFullImagePath('10127'),
    [UnitCode.x_iblis]: getUnitFullImagePath('10128'),
    [UnitCode.w_evie]: getUnitFullImagePath('10129'),
    [UnitCode.salina]: getUnitFullImagePath('10130'),
    [UnitCode.noma]: getUnitFullImagePath('10022'),
    [UnitCode.belladonna]: getUnitFullImagePath('10023'),
    [UnitCode.nanami]: getUnitFullImagePath('10133'),
    [UnitCode.w_noel]: getUnitFullImagePath('10134'),
    [UnitCode.w_mesmiia]: getUnitFullImagePath('10135'),
    [UnitCode.angelina]: getUnitFullImagePath('10136'),
    [UnitCode.w_lillane]: getUnitFullImagePath('10137'),
    [UnitCode.p_lulu]: getUnitFullImagePath('10138'),
    [UnitCode.p_tyrella]: getUnitFullImagePath('10139'),
    [UnitCode.lelya]: getUnitFullImagePath('10140'),
    [UnitCode.a_nana]: getUnitFullImagePath('10141'),
    [UnitCode.s_chizuru]: getUnitFullImagePath('10142'),
    [UnitCode.s_salucia]: getUnitFullImagePath('10143'),
    [UnitCode.s_caesar]: getUnitFullImagePath('10144'),
    [UnitCode.s_satan]: getUnitFullImagePath('10145'),
    [UnitCode.d_minayomi]: getUnitFullImagePath('10146'),
    [UnitCode.oniyoiki]: getUnitFullImagePath('10147'),
    [UnitCode.beer_shizuka]: getUnitFullImagePath('10148'),
    [UnitCode.tsubaki]: getUnitFullImagePath('10149'),
    [UnitCode.amethystina]: getUnitFullImagePath('10044'),
    [UnitCode.bg_ayane]: getUnitFullImagePath('10150'),
    [UnitCode.bg_iblis]: getUnitFullImagePath('10151'),
    [UnitCode.susan]: getUnitFullImagePath('10152'),
    [UnitCode.h_satan]: getUnitFullImagePath('10153'),
    [UnitCode.m_nanami]: getUnitFullImagePath('10154'),
    [UnitCode.m_ks8]: getUnitFullImagePath('10155'),
    [UnitCode.x_baal]: getUnitFullImagePath('10156'),
    [UnitCode.x_muila]: getUnitFullImagePath('10157'),
    [UnitCode.x_britney]: getUnitFullImagePath('10158'),
    [UnitCode.x_ichika]: getUnitFullImagePath('10175'),
    [UnitCode.ny_fiora]: getUnitFullImagePath('10159'),
    [UnitCode.zaskia]: getUnitFullImagePath('10161'),
    [UnitCode.p_aiko]: getUnitFullImagePath('10162'),
    [UnitCode.ni_caesar]: getUnitFullImagePath('10163'),
    [UnitCode.f_kana]: getUnitFullImagePath('10164'),
    [UnitCode.star_mia]: getUnitFullImagePath('10165'),
    [UnitCode.star_annee]: getUnitFullImagePath('10166'),
    [UnitCode.bedard]: getUnitFullImagePath('10176'),
    [UnitCode.c_noel]: getUnitFullImagePath('10167'),
    [UnitCode.eunice]: getUnitFullImagePath('10168'),
    [UnitCode.momDaphne]: getUnitFullImagePath('10169'),
    [UnitCode.w_tsubaki]: getUnitFullImagePath('10170'),
    [UnitCode.ss_iblis]: getUnitFullImagePath('10171'),
    [UnitCode.s_evie]: getUnitFullImagePath('10172'),
    [UnitCode.s_noma]: getUnitFullImagePath('10173'),
    [UnitCode.forneusa]: getUnitFullImagePath('10174'),
    [UnitCode.bu_ayane]: getUnitFullImagePath('10160'),
    [UnitCode.sky_nanami]: getUnitFullImagePath('10177'),
    [UnitCode.sky_baal]: getUnitFullImagePath('10178'),
}

export const FullImage = {
    ...N,
    ...R,
    ...SR,
    ...SSR
}