import { UnitCode } from '@/plugins/utils/enums';

const cdnURL = `https://cdn.tkfmdata.com`

function getUnitSelectionPath(id: string): string{
    return `${cdnURL}/character/selection/cs${id}_0_0.png`;
}

const N = {
    [UnitCode.saria]: getUnitSelectionPath('10901'),
    [UnitCode.petra]: getUnitSelectionPath('10902'),
    [UnitCode.flay]: getUnitSelectionPath('10903'),
    [UnitCode.manuella]: getUnitSelectionPath('10904'),
    [UnitCode.kikyou]: getUnitSelectionPath('10905'),
    [UnitCode.kaede]: getUnitSelectionPath('10906'),
    [UnitCode.ola]: getUnitSelectionPath('10907'),
    [UnitCode.kani]: getUnitSelectionPath('10908'),
    [UnitCode.charlene]: getUnitSelectionPath('10909'),
    [UnitCode.martina]: getUnitSelectionPath('10910'),
    [UnitCode.clarie]: getUnitSelectionPath('10911'),
    [UnitCode.lori]: getUnitSelectionPath('10912'),
    [UnitCode.minnow]: getUnitSelectionPath('10913'),
    [UnitCode.lamia]: getUnitSelectionPath('10914'),
    [UnitCode.harpy]: getUnitSelectionPath('10915'),
    [UnitCode.anna]: getUnitSelectionPath('10916'),
    [UnitCode.blaire]: getUnitSelectionPath('10917'),
    [UnitCode.natasha]: getUnitSelectionPath('10918'),
    [UnitCode.prototype]: getUnitSelectionPath('10922'),
    [UnitCode.punishment]: getUnitSelectionPath('10919'),
    [UnitCode.bliss]: getUnitSelectionPath('10920'),
    [UnitCode.mareyl]: getUnitSelectionPath('10923'),
    [UnitCode.mumu]: getUnitSelectionPath('10924'),
    [UnitCode.molly]: getUnitSelectionPath('10921'),
    [UnitCode.anya]: getUnitSelectionPath('10933'),
}

const R = {
    [UnitCode.irene]: getUnitSelectionPath('10801'),
    [UnitCode.nana]: getUnitSelectionPath('10802'),
    [UnitCode.iris]: getUnitSelectionPath('10803'),
    [UnitCode.dora]: getUnitSelectionPath('10804'),
    [UnitCode.sable]: getUnitSelectionPath('10805'),
    [UnitCode.marlene]: getUnitSelectionPath('10806'),
    [UnitCode.yoi]: getUnitSelectionPath('10807'),
    [UnitCode.shiraka]: getUnitSelectionPath('10808'),
    [UnitCode.panana]: getUnitSelectionPath('10812'),
    [UnitCode.sophie]: getUnitSelectionPath('10810'),
    [UnitCode.jolina]: getUnitSelectionPath('10811'),
    [UnitCode.mia]: getUnitSelectionPath('10809'),
    [UnitCode.iyan]: getUnitSelectionPath('10813'),
}

const SR = {
    [UnitCode.aiko]: getUnitSelectionPath('10009'),
    [UnitCode.leona]: getUnitSelectionPath('10010'),
    [UnitCode.fiora]: getUnitSelectionPath('10011'),
    [UnitCode.ritsuki]: getUnitSelectionPath('10012'),
    [UnitCode.minayomi]: getUnitSelectionPath('10013'),
    [UnitCode.shizuka]: getUnitSelectionPath('10014'),
    [UnitCode.juneau]: getUnitSelectionPath('10015'),
    [UnitCode.britney]: getUnitSelectionPath('10016'),
    [UnitCode.nafrala]: getUnitSelectionPath('10036'),
    [UnitCode.tyrella]: getUnitSelectionPath('10038'),
    [UnitCode.teresa]: getUnitSelectionPath('10061'),
    [UnitCode.pulicia]: getUnitSelectionPath('10051'),
    [UnitCode.janelle]: getUnitSelectionPath('10046'),
    [UnitCode.tanocia]: getUnitSelectionPath('10055'),
    [UnitCode.yingying]: getUnitSelectionPath('10041'),
}

const SSR = {
    [UnitCode.baal]: getUnitSelectionPath('10001'),
    [UnitCode.satan]: getUnitSelectionPath('10002'),
    [UnitCode.iblis]: getUnitSelectionPath('10003'),
    [UnitCode.salucia]: getUnitSelectionPath('10004'),
    [UnitCode.lana]: getUnitSelectionPath('10005'),
    [UnitCode.lulu]: getUnitSelectionPath('10006'),
    [UnitCode.f_baal]: getUnitSelectionPath('10017'),
    [UnitCode.i_iblis]: getUnitSelectionPath('10025'),
    [UnitCode.noel]: getUnitSelectionPath('10026'),
    [UnitCode.ks8]: getUnitSelectionPath('10008'),
    [UnitCode.mesmiia]: getUnitSelectionPath('10037'),
    [UnitCode.e_satan]: getUnitSelectionPath('10027'),
    [UnitCode.chizuru]: getUnitSelectionPath('10028'),
    [UnitCode.daphne]: getUnitSelectionPath('10057'),
    [UnitCode.s_shizuka]: getUnitSelectionPath('10029'),
    [UnitCode.s_lulu]: getUnitSelectionPath('10030'),
    [UnitCode.s_ks8]: getUnitSelectionPath('10031'),
    [UnitCode.s_nana]: getUnitSelectionPath('10032'),
    [UnitCode.milae]: getUnitSelectionPath('10007'),
    [UnitCode.asida]: getUnitSelectionPath('10034'),
    [UnitCode.asina]: getUnitSelectionPath('10035'),
    [UnitCode.aridya]: getUnitSelectionPath('10033'),
    [UnitCode.lotiya]: getUnitSelectionPath('10039'),
    [UnitCode.fufu]: getUnitSelectionPath('10058'),
    [UnitCode.hm_fiora]: getUnitSelectionPath('10060'),
    [UnitCode.karina]: getUnitSelectionPath('10056'),
    [UnitCode.ibuki]: getUnitSelectionPath('10045'),
    [UnitCode.h_britney]: getUnitSelectionPath('10040'),
    [UnitCode.h_salucia]: getUnitSelectionPath('10043'),
    [UnitCode.inori]: getUnitSelectionPath('10059'),
    [UnitCode.sakuya]: getUnitSelectionPath('10083'),
    [UnitCode.x_aiko]: getUnitSelectionPath('10052'),
    [UnitCode.x_lana]: getUnitSelectionPath('10053'),
    [UnitCode.evie]: getUnitSelectionPath('10054'),
    [UnitCode.tm_minayomi]: getUnitSelectionPath('10067'),
    [UnitCode.tm_ritsuki]: getUnitSelectionPath('10079'),
    [UnitCode.b_baal]: getUnitSelectionPath('10072'),
    [UnitCode.b_iblis]: getUnitSelectionPath('10081'),
    [UnitCode.b_satan]: getUnitSelectionPath('10082'),
    [UnitCode.miru]: getUnitSelectionPath('10084'),
    [UnitCode.uruta]: getUnitSelectionPath('10018'),
    [UnitCode.ayane]: getUnitSelectionPath('10019'),
    [UnitCode.muila]: getUnitSelectionPath('10020'),
    [UnitCode.f_caesar]: getUnitSelectionPath('10050'),
    [UnitCode.w_chizuru]: getUnitSelectionPath('10075'),
    [UnitCode.w_lulu]: getUnitSelectionPath('10076'),
    [UnitCode.faya]: getUnitSelectionPath('10049'),
    [UnitCode.usagihime]: getUnitSelectionPath('10100'),
    [UnitCode.s_iblis]: getUnitSelectionPath('10042'),
    [UnitCode.s_milae]: getUnitSelectionPath('10090'),
    [UnitCode.s_noel]: getUnitSelectionPath('10091'),
    [UnitCode.s_aridya]: getUnitSelectionPath('10092'),
    [UnitCode.ichika]: getUnitSelectionPath('10074'),
    [UnitCode.kana]: getUnitSelectionPath('10085'),
    [UnitCode.q_asida]: getUnitSelectionPath('10088'),
    [UnitCode.q_asina]: getUnitSelectionPath('10089'),
    [UnitCode.emily]: getUnitSelectionPath('10063'),
    [UnitCode.anjelica]: getUnitSelectionPath('10066'),
    [UnitCode.c1_nana]: getUnitSelectionPath('10093'),
    [UnitCode.geneva]: getUnitSelectionPath('10094'),
    [UnitCode.lotus]: getUnitSelectionPath('10068'),
    [UnitCode.didi]: getUnitSelectionPath('10047'),
    [UnitCode.h_leona]: getUnitSelectionPath('10095'),
    [UnitCode.h_lotiya]: getUnitSelectionPath('10096'),
    [UnitCode.sherana]: getUnitSelectionPath('10062'),
    [UnitCode.elizabeth]: getUnitSelectionPath('10024'),
    [UnitCode.xx_aiko]: getUnitSelectionPath('10097'),
    [UnitCode.x_shizuka]: getUnitSelectionPath('10098'),
    [UnitCode.shiro]: getUnitSelectionPath('10021'),
    [UnitCode.ny_salucia]: getUnitSelectionPath('10106'),
    [UnitCode.ny_lana]: getUnitSelectionPath('10107'),
    [UnitCode.v_baal]: getUnitSelectionPath('10108'),
    [UnitCode.v_iblis]: getUnitSelectionPath('10109'),
    [UnitCode.v_satan]: getUnitSelectionPath('10110'),
    [UnitCode.lillane]: getUnitSelectionPath('10069'),
    [UnitCode.c_lulu]: getUnitSelectionPath('10078'),
    [UnitCode.m_juneau]: getUnitSelectionPath('10114'),
    [UnitCode.m_britney]: getUnitSelectionPath('10115'),
    [UnitCode.momo]: getUnitSelectionPath('10048'),
    [UnitCode.n_caesar]: getUnitSelectionPath('10113'),
    [UnitCode.d_irene]: getUnitSelectionPath('10111'),
    [UnitCode.s_ayane]: getUnitSelectionPath('10116'),
    [UnitCode.s_baal]: getUnitSelectionPath('10117'),
    [UnitCode.s_fiora]: getUnitSelectionPath('10118'),
    [UnitCode.s_aiko]: getUnitSelectionPath('10119'),
    [UnitCode.o_lana]: getUnitSelectionPath('10120'),
    [UnitCode.o_nana]: getUnitSelectionPath('10121'),
    [UnitCode.sasha]: getUnitSelectionPath('10071'),
    [UnitCode.bayliss]: getUnitSelectionPath('10077'),
    [UnitCode.a_usagihime]: getUnitSelectionPath('10122'),
    [UnitCode.d_miru]: getUnitSelectionPath('10123'),
    [UnitCode.nyoro]: getUnitSelectionPath('10124'),
    [UnitCode.h_ayane]: getUnitSelectionPath('10125'),
    [UnitCode.h_shiro]: getUnitSelectionPath('10126'),
    [UnitCode.inase]: getUnitSelectionPath('10131'),
    [UnitCode.cartilla]: getUnitSelectionPath('10132'),
    [UnitCode.x_aridya]: getUnitSelectionPath('10127'),
    [UnitCode.x_iblis]: getUnitSelectionPath('10128'),
    [UnitCode.w_evie]: getUnitSelectionPath('10129'),
    [UnitCode.salina]: getUnitSelectionPath('10130'),
    [UnitCode.noma]: getUnitSelectionPath('10022'),
    [UnitCode.belladonna]: getUnitSelectionPath('10023'),
    [UnitCode.nanami]: getUnitSelectionPath('10133'),
    [UnitCode.w_noel]: getUnitSelectionPath('10134'),
    [UnitCode.w_mesmiia]: getUnitSelectionPath('10135'),
    [UnitCode.angelina]: getUnitSelectionPath('10136'),
    [UnitCode.w_lillane]: getUnitSelectionPath('10137'),
    [UnitCode.p_lulu]: getUnitSelectionPath('10138'),
    [UnitCode.p_tyrella]: getUnitSelectionPath('10139'),
    [UnitCode.lelya]: getUnitSelectionPath('10140'),
    [UnitCode.a_nana]: getUnitSelectionPath('10141'),
    [UnitCode.s_chizuru]: getUnitSelectionPath('10142'),
    [UnitCode.s_salucia]: getUnitSelectionPath('10143'),
    [UnitCode.s_caesar]: getUnitSelectionPath('10144'),
    [UnitCode.s_satan]: getUnitSelectionPath('10145'),
    [UnitCode.d_minayomi]: getUnitSelectionPath('10146'),
    [UnitCode.oniyoiki]: getUnitSelectionPath('10147'),
    [UnitCode.beer_shizuka]: getUnitSelectionPath('10148'),
    [UnitCode.tsubaki]: getUnitSelectionPath('10149'),
    [UnitCode.amethystina]: getUnitSelectionPath('10044'),
    [UnitCode.bg_ayane]: getUnitSelectionPath('10150'),
    [UnitCode.bg_iblis]: getUnitSelectionPath('10151'),
    [UnitCode.susan]: getUnitSelectionPath('10152'),
    [UnitCode.h_satan]: getUnitSelectionPath('10153'),
    [UnitCode.m_nanami]: getUnitSelectionPath('10154'),
    [UnitCode.m_ks8]: getUnitSelectionPath('10155'),
    [UnitCode.x_baal]: getUnitSelectionPath('10156'),
    [UnitCode.x_muila]: getUnitSelectionPath('10157'),
    [UnitCode.x_britney]: getUnitSelectionPath('10158'),
    [UnitCode.x_ichika]: getUnitSelectionPath('10175'),
    [UnitCode.ny_fiora]: getUnitSelectionPath('10159'),
    [UnitCode.zaskia]: getUnitSelectionPath('10161'),
    [UnitCode.p_aiko]: getUnitSelectionPath('10162'),
    [UnitCode.ni_caesar]: getUnitSelectionPath('10163'),
    [UnitCode.f_kana]: getUnitSelectionPath('10164'),
    [UnitCode.star_mia]: getUnitSelectionPath('10165'),
    [UnitCode.star_annee]: getUnitSelectionPath('10166'),
    [UnitCode.bedard]: getUnitSelectionPath('10176'),
    [UnitCode.c_noel]: getUnitSelectionPath('10167'),
    [UnitCode.eunice]: getUnitSelectionPath('10168'),
    [UnitCode.momDaphne]: getUnitSelectionPath('10169'),
    [UnitCode.w_tsubaki]: getUnitSelectionPath('10170'),
    [UnitCode.ss_iblis]: getUnitSelectionPath('10171'),
    [UnitCode.s_evie]: getUnitSelectionPath('10172'),
    [UnitCode.s_noma]: getUnitSelectionPath('10173'),
    [UnitCode.forneusa]: getUnitSelectionPath('10174'),
    [UnitCode.bu_ayane]: getUnitSelectionPath('10160'),
    [UnitCode.sky_nanami]: getUnitSelectionPath('10177'),
    [UnitCode.sky_baal]: getUnitSelectionPath('10178'),
    [UnitCode.n_lulu]: getUnitSelectionPath('10179'),
    [UnitCode.yuri]: getUnitSelectionPath('10180'),
    [UnitCode.l_ayane]: getUnitSelectionPath('10181'),
    [UnitCode.ria]: getUnitSelectionPath('10182'),
    [UnitCode.g_britney]: getUnitSelectionPath('10183'),
    [UnitCode.h_momDaphne]: getUnitSelectionPath('10184'),
    [UnitCode.lilinor]: getUnitSelectionPath('10185'),
    [UnitCode.m_salucia]: getUnitSelectionPath('10186'),
    [UnitCode.lutty]: getUnitSelectionPath('10187'),
}

export const Selection = {
    ...N,
    ...R,
    ...SR,
    ...SSR
}