export enum Locale {
    tc = 'tc',
    sc = 'sc',
    en = 'en',
    jp = 'jp',
    kr = 'kr',
}

export enum VoiceLocale {
    jp = 'jp',
}

export enum ErrorCode {
    PAGE_NOT_FOUND = 404,
    UNKNOWN_ERROR = 500,
    CANNOT_FIND_CHARACTER = 801,
    CANNOT_FIND_EVENT = 802,
    CANNOT_FIND_ART = 803,
}

export enum ErrorMessage {
    PAGE_NOT_FOUND = 'PAGE_NOT_FOUND',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    CANNOT_FIND_CHARACTER = 'CANNOT_FIND_CHARACTER',
    CANNOT_FIND_EVENT = 'CANNOT_FIND_EVENT',
    CANNOT_FIND_ART = 'CANNOT_FIND_ART',
}

export enum LogType {
    NEW = 'NEW',
    FIX = 'FIX',
    CHANGE = 'CHANGE',
    OTHER = 'OTHER',
}

export enum LogGroup {
    UNIT = 'UNIT',
    EVENT = 'EVENT',
    ART = 'ART',
    SKILL = 'SKILL',
    LIBERATE = 'LIBERATE',
    OUTFIT = 'OUTFIT',
    PUZZLE = 'PUZZLE',
    GENERAL = 'GENERAL',
}

export enum Element {
    FIRE = 'FIRE',
    WATER = 'WATER',
    WIND = 'WIND',
    LIGHT = 'LIGHT',
    DARK = 'DARK',
}

export enum Position {
    ATTACKER = 'ATTACKER',
    OBSTRUCTER = 'OBSTRUCTER',
    PROTECTOR = 'PROTECTOR',
    HEALER = 'HEALER',
    SUPPORTER = 'SUPPORTER',
}

export enum Rarity {
    SSR = 'SSR',
    SR = 'SR',
    R = 'R',
    N = 'N',
}

export enum SkillType {
    BASE_STAT = 'BASE_STAT',
    SKILL_S = 'SKILL_S',
    SKILL_1 = 'SKILL_1',
    SKILL_2 = 'SKILL_2',
    SKILL_3 = 'SKILL_3',
    SKILL_4 = 'SKILL_4',
    SKILL_5 = 'SKILL_5',
    ATTACK = 'ATTACK',
    LEADER = 'LEADER',
    PASSIVE_1 = 'PASSIVE_1',
    PASSIVE_2 = 'PASSIVE_2',
    PASSIVE_3 = 'PASSIVE_3',
    GENERAL_1 = 'GENERAL_1',
    GENERAL_2 = 'GENERAL_2',
    DISPATCH = 'DISPATCH',
}

export enum LiberationStage {
    LIBERATION_0 = 'LIBERATION_0',
    LIBERATION_1 = 'LIBERATION_1',
    LIBERATION_2 = 'LIBERATION_2',
    LIBERATION_3 = 'LIBERATION_3',
}

export enum TagType {
    ELEMENT = 'ELEMENT',
    POSITION = 'POSITION',
    SPECIES = 'SPECIES',
    BODY = 'BODY',
    BREAST = 'BREAST',
    CLASS = 'CLASS',
    OTHER = 'OTHER',
}

export enum PotentialType {
    ATTACK = 'ATTACK',
    DEFENCE = 'DEFENCE',
    BALANCE = 'BALANCE',
    NR = 'NR',
}

export enum PotentialBuffType {
    ATK = 'ATK',
    HP = 'HP',
    PASSIVE = 'PASSIVE',
}

export enum VoiceType {
    GREET = 'GREET',
    CONFUSED = 'CONFUSED',
    HAPPY = 'HAPPY',
    ANGRY = 'ANGRY',
    SAD = 'SAD',
    FURIOUS = 'FURIOUS',
    AGREE = 'AGREE',
    DISAGREE = 'DISAGREE',
    PROMISE = 'PROMISE',
    ATTACK = 'ATTACK',
    SKILL = 'SKILL',
    TAKE_DAMAGE = 'TAKE_DAMAGE',
    DEATH = 'DEATH',
    DISCIPLINE_1 = 'DISCIPLINE_1',
    DISCIPLINE_2 = 'DISCIPLINE_2',
    DISCIPLINE_3 = 'DISCIPLINE_3',
    ORGASM = 'ORGASM',
    CHARACTER_FEATURE_1 = 'CHARACTER_FEATURE_1',
    CHARACTER_FEATURE_2 = 'CHARACTER_FEATURE_2',
    CHARACTER_FEATURE_3 = 'CHARACTER_FEATURE_3',
    CHARACTER_FEATURE_4 = 'CHARACTER_FEATURE_4',
    CHARACTER_FEATURE_5 = 'CHARACTER_FEATURE_5',
    VICTORY = 'VICTORY',
    DEFEAT = 'DEFEAT',
}

export enum ItemType {
    GENERAL = 'GENERAL',
    EVOLVE = 'EVOLVE',
    POTENTIAL = 'POTENTIAL',
    POTENTIAL_ADVANCED = 'POTENTIAL_ADVANCED',
    DISCIPLINE = 'DISCIPLINE',
    EXP = 'EXP'
}

export enum ItemCode {
    SLIVER_COIN = 'SLIVER_COIN',
    NAMELESS = 'NAMELESS',
    LIBERATE_STONE = 'LIBERATE_STONE',
    FLAWLESS = 'FLAWLESS',
    SKILL_FRAGMENT = 'SKILL_FRAGMENT',
    SKILL_STONE = 'SKILL_STONE',
    EVOLVE_FIRE_LV1 = 'EVOLVE_FIRE_LV1',
    EVOLVE_FIRE_LV2 = 'EVOLVE_FIRE_LV2',
    EVOLVE_FIRE_LV3 = 'EVOLVE_FIRE_LV3',
    EVOLVE_FIRE_LV4 = 'EVOLVE_FIRE_LV4',
    EVOLVE_WATER_LV1 = 'EVOLVE_WATER_LV1',
    EVOLVE_WATER_LV2 = 'EVOLVE_WATER_LV2',
    EVOLVE_WATER_LV3 = 'EVOLVE_WATER_LV3',
    EVOLVE_WATER_LV4 = 'EVOLVE_WATER_LV4',
    EVOLVE_WIND_LV1 = 'EVOLVE_WIND_LV1',
    EVOLVE_WIND_LV2 = 'EVOLVE_WIND_LV2',
    EVOLVE_WIND_LV3 = 'EVOLVE_WIND_LV3',
    EVOLVE_WIND_LV4 = 'EVOLVE_WIND_LV4',
    EVOLVE_LIGHT_LV1 = 'EVOLVE_LIGHT_LV1',
    EVOLVE_LIGHT_LV2 = 'EVOLVE_LIGHT_LV2',
    EVOLVE_LIGHT_LV3 = 'EVOLVE_LIGHT_LV3',
    EVOLVE_LIGHT_LV4 = 'EVOLVE_LIGHT_LV4',
    EVOLVE_DARK_LV1 = 'EVOLVE_DARK_LV1',
    EVOLVE_DARK_LV2 = 'EVOLVE_DARK_LV2',
    EVOLVE_DARK_LV3 = 'EVOLVE_DARK_LV3',
    EVOLVE_DARK_LV4 = 'EVOLVE_DARK_LV4',
    CLAW_LV1 = 'CLAW_LV1',
    CLAW_LV2 = 'CLAW_LV2',
    CLAW_LV3 = 'CLAW_LV3',
    IRON_LV1 = 'IRON_LV1',
    IRON_LV2 = 'IRON_LV2',
    IRON_LV3 = 'IRON_LV3',
    WATER_LV1 = 'WATER_LV1',
    WATER_LV2 = 'WATER_LV2',
    WATER_LV3 = 'WATER_LV3',
    MIXTURE_LV1 = 'MIXTURE_LV1',
    MIXTURE_LV2 = 'MIXTURE_LV2',
    MIXTURE_LV3 = 'MIXTURE_LV3',
    DUST_LV1 = 'DUST_LV1',
    DUST_LV2 = 'DUST_LV2',
    DUST_LV3 = 'DUST_LV3',
    HORN_LV1 = 'HORN_LV1',
    HORN_LV2 = 'HORN_LV2',
    SLIVER_LV1 = 'SLIVER_LV1',
    SLIVER_LV2 = 'SLIVER_LV2',
    OIL_LV1 = 'OIL_LV1',
    OIL_LV2 = 'OIL_LV2',
    CRYSTAL_LV1 = 'CRYSTAL_LV1',
    CRYSTAL_LV2 = 'CRYSTAL_LV2',
    FANG_LV1 = 'FANG_LV1',
    FANG_LV2 = 'FANG_LV2',
    BEAK_LV1 = 'BEAK_LV1',
    BEAK_LV2 = 'BEAK_LV2',
    SKIN_LV1 = 'SKIN_LV1',
    SKIN_LV2 = 'SKIN_LV2',
    BOOK_LV1 = 'BOOK_LV1',
    BOOK_LV2 = 'BOOK_LV2',
    FEATHER_LV1 = 'FEATHER_LV1',
    FEATHER_LV2 = 'FEATHER_LV2',
    WEB_LV1 = 'WEB_LV1',
    WEB_LV2 = 'WEB_LV2',
    DISCIPLINE_FIRE_LV1 = 'DISCIPLINE_FIRE_LV1',
    DISCIPLINE_FIRE_LV2 = 'DISCIPLINE_FIRE_LV2',
    DISCIPLINE_FIRE_LV3 = 'DISCIPLINE_FIRE_LV3',
    DISCIPLINE_WATER_LV1 = 'DISCIPLINE_WATER_LV1',
    DISCIPLINE_WATER_LV2 = 'DISCIPLINE_WATER_LV2',
    DISCIPLINE_WATER_LV3 = 'DISCIPLINE_WATER_LV3',
    DISCIPLINE_WIND_LV1 = 'DISCIPLINE_WIND_LV1',
    DISCIPLINE_WIND_LV2 = 'DISCIPLINE_WIND_LV2',
    DISCIPLINE_WIND_LV3 = 'DISCIPLINE_WIND_LV3',
    DISCIPLINE_LIGHT_LV1 = 'DISCIPLINE_LIGHT_LV1',
    DISCIPLINE_LIGHT_LV2 = 'DISCIPLINE_LIGHT_LV2',
    DISCIPLINE_LIGHT_LV3 = 'DISCIPLINE_LIGHT_LV3',
    DISCIPLINE_DARK_LV1 = 'DISCIPLINE_DARK_LV1',
    DISCIPLINE_DARK_LV2 = 'DISCIPLINE_DARK_LV2',
    DISCIPLINE_DARK_LV3 = 'DISCIPLINE_DARK_LV3',
    DISCIPLINE_FRUIT = 'DISCIPLINE_FRUIT',
    EXP_LV1 = 'EXP_LV1',
    EXP_LV2 = 'EXP_LV2',
    EXP_LV3 = 'EXP_LV3',
    EXP_LV4 = 'EXP_LV4',
}

export enum DispatchType {
    CAESAR_ROOM = 'CAESAR_ROOM',
    DUNGEON = 'DUNGEON',
    TRAINING_CENTER = 'TRAINING_CENTER',
    TREASURE_ROOM = 'TREASURE_ROOM',
    SEALED_CHAMBER = 'SEALED_CHAMBER',
}

export enum DispatchSkillType {
    EMPTY_HAND = 'EMPTY_HAND',
    ENHANCE_MATERIAL = 'ENHANCE_MATERIAL',
    NORMAL_SEX_TOY = 'NORMAL_SEX_TOY',
    RARE_SEX_TOY = 'RARE_SEX_TOY',
    RARE_NORMAL_SEX_TOY = 'RARE_NORMAL_SEX_TOY',
    EXPERIENCE_POTION = 'EXPERIENCE_POTION',
    PURCHASE_PERMITS = 'PURCHASE_PERMITS',
}

export enum TagID {
    ELEMENT_FIRE = 1,
    ELEMENT_WATER = 2,
    ELEMENT_WIND = 3,
    ELEMENT_LIGHT = 4,
    ELEMENT_DARK = 5,
    POSITION_ATTACKER = 6,
    POSITION_PROTECTOR = 7,
    POSITION_HEALER = 8,
    POSITION_OBSTRUCTER = 9,
    POSITION_SUPPORTER = 10,
    SPECIES_HUMAN = 11,
    SPECIES_DEMON = 12,
    SPECIES_DEMIHUMAN = 13,
    BODY_SMALL_SIZED = 14,
    BODY_MEDIUM_SIZED = 15,
    BREAST_FLAT_TITS = 16,
    BREAST_HOT_TITS = 17,
    BREAST_GIANT_TITS = 18,
    CLASS_SOLDIER = 19,
    CLASS_ELITE = 20,
    CLASS_LEADER = 21,
    OTHER_DAMAGE_OUTPUT = 22,
    OTHER_PROTECTION = 23,
    OTHER_DEFENSE = 24,
    OTHER_RECOVERY = 25,
    OTHER_INTERFERENCE = 26,
    OTHER_SUPPORT = 27,
    OTHER_WEAKEN = 28,
    OTHER_EXPLOSIVENESS = 29,
    OTHER_SURVIVABILLITY = 30,
    OTHER_MORE_POWER = 31,
    OTHER_AOE = 32,
    OTHER_COUNTERSTRIKE = 33,
}

export enum ArtAuthorType {
    AUTHOR = 'AUTHOR',
    OWNER = 'OWNER'
}

export enum ArtSource {
    OFFICAL = 'OFFICAL',
    FANART = 'FANART'
}

export enum ArtType {
    PAINTING = 'PAINTING',
    STICKER = 'STICKER',
    COMIC = 'COMIC',
    FICTION = 'FICTION',
    VIDEO = 'VIDEO',
    OTHER = 'OTHER'
}

export enum FanartOwner {
    DOKGUN = '독군 Dokgun',
    NOEL = '黑白好哇塞',
    MIMI_MAOMAO = '咪咪貓貓',
    MOON_RABBIT = '月兔管理官',
    LITTLE_PEA = '三重小豌豌',
    ANNA_PHOENIX = '真吾鳳',
    XXBM = 'XXBM 小小布魔',
    VV = '森屿海盐vv',
    C = '嗯C郎',
}

export enum PuzzleType {
    EVENT = 'EVENT',
    HUMAN = 'HUMAN',
    DEMON = 'DEMON',
    SKY = 'SKY',
}

export enum PuzzleCode {
    EVENT_2021_SUMMER_1 = 'EVENT_2021_SUMMER_1',
    EVENT_2021_SUMMER_1_DMM = 'EVENT_2021_SUMMER_1_DMM',
    EVENT_2021_SUMMER_2 = 'EVENT_2021_SUMMER_2',
    EVENT_2021_SUMMER_3 = 'EVENT_2021_SUMMER_3',
    EVENT_2021_SUMMER_4 = 'EVENT_2021_SUMMER_4',
    EVENT_2021_XMAS_1 = 'EVENT_2021_XMAS_1',
    EVENT_2021_XMAS_2 = 'EVENT_2021_XMAS_2',
    EVENT_2022_SUMMER_1 = 'EVENT_2022_SUMMER_1',
    EVENT_2022_SUMMER_2 = 'EVENT_2022_SUMMER_2',
    EVENT_2022_SUMMER_3 = 'EVENT_2022_SUMMER_3',
    EVENT_2022_SUMMER_4 = 'EVENT_2022_SUMMER_4',
    EVENT_2022_XMAS_1 = 'EVENT_2022_XMAS_1',
    EVENT_2023_CNY_1 = 'EVENT_2023_CNY_1',
    EVENT_2023_SUMMER_1 = 'EVENT_2023_SUMMER_1',
    EVENT_2023_SUMMER_2 = 'EVENT_2023_SUMMER_2',
    EVENT_2023_SUMMER_3 = 'EVENT_2023_SUMMER_3',
    EVENT_2023_SUMMER_4 = 'EVENT_2023_SUMMER_4',
    EVENT_2023_XMAS_1 = 'EVENT_2023_XMAS_1',
    EVENT_2023_XMAS_2 = 'EVENT_2023_XMAS_2',
    EVENT_2024_SUMMER_1 = 'EVENT_2024_SUMMER_1',
    EVENT_2024_SUMMER_2 = 'EVENT_2024_SUMMER_2',
    EVENT_2024_SUMMER_3 = 'EVENT_2024_SUMMER_3',
    EVENT_2024_SUMMER_4 = 'EVENT_2024_SUMMER_4',
    EVENT_2024_XMAS_1 = 'EVENT_2024_XMAS_1',
    EVENT_2024_XMAS_2 = 'EVENT_2024_XMAS_2',
    EVENT_2025_SUMMER_1 = 'EVENT_2025_SUMMER_1',
    EVENT_2025_SUMMER_2 = 'EVENT_2025_SUMMER_2',
    EVENT_2025_SUMMER_3 = 'EVENT_2025_SUMMER_3',
    EVENT_2025_SUMMER_4 = 'EVENT_2025_SUMMER_4',
    HUMAN_SARIA = 'HUMAN_SARIA',
    HUMAN_PETRA = 'HUMAN_PETRA',
    HUMAN_KIKYOU = 'HUMAN_KIKYOU',
    HUMAN_KAEDE = 'HUMAN_KAEDE',
    HUMAN_OLA = 'HUMAN_OLA',
    HUMAN_KANI = 'HUMAN_KANI',
    HUMAN_CHARLENE = 'HUMAN_CHARLENE',
    HUMAN_MARTINA = 'HUMAN_MARTINA',
    HUMAN_CLARIE = 'HUMAN_CLARIE',
    HUMAN_ANNA = 'HUMAN_ANNA',
    HUMAN_BLAIRE = 'HUMAN_BLAIRE',
    HUMAN_NATASHA = 'HUMAN_NATASHA',
    HUMAN_MOLLY = 'HUMAN_MOLLY',
    HUMAN_ANYA = 'HUMAN_ANYA',
    DEMON_FLAY = 'DEMON_FLAY',
    DEMON_MANUELLA = 'DEMON_MANUELLA',
    DEMON_LORI = 'DEMON_LORI',
    DEMON_MINNOW = 'DEMON_MINNOW',
    DEMON_LAMIA = 'DEMON_LAMIA',
    DEMON_HARPY = 'DEMON_HARPY',
    DEMON_MAREYL = 'DEMON_MAREYL',
    DEMON_MUMU = 'DEMON_MUMU',
    SKY_PUNISHMENT = 'SKY_PUNISHMENT',
    SKY_BLISS = 'SKY_BLISS',
}

export enum EventType {
    CHALLENGE = 'CHALLENGE',
    POINT = 'POINT',
    EVOLVE = 'EVOLVE',
    DISCIPLINE = 'DISCIPLINE',
    POTENTIAL = 'POTENTIAL',
    SLIVER = 'SLIVER',
    SIDESTORY = 'SIDESTORY',
    SPIRE = 'SPIRE',
    TIMERIFT = 'TIMERIFT',
    GUILDBOSS = 'GUILDBOSS',
    SPECIAL = 'SPECIAL',
}

export enum UnitCode {
    saria = 'N-001',
    petra = 'N-002',
    flay = 'N-003',
    manuella = 'N-004',
    kikyou = 'N-005',
    kaede = 'N-006',
    ola = 'N-007',
    kani = 'N-008',
    charlene = 'N-009',
    martina = 'N-010',
    clarie = 'N-011',
    lori = 'N-012',
    minnow = 'N-013',
    lamia = 'N-014',
    harpy = 'N-015',
    anna = 'N-016',
    blaire = 'N-017',
    natasha = 'N-018',
    prototype = 'N-019',
    punishment = 'N-020',
    bliss = 'N-021',
    mareyl = 'N-022',
    mumu = 'N-023',
    molly = 'N-024',
    anya = 'N-025',
    irene = 'R-001',
    nana = 'R-002',
    iris = 'R-003',
    dora = 'R-004',
    sable = 'R-005',
    marlene = 'R-006',
    yoi = 'R-007',
    shiraka = 'R-008',
    panana = 'R-009',
    sophie = 'R-010',
    jolina = 'R-011',
    mia = 'R-012',
    iyan = 'R-013',
    aiko = 'SR-001',
    leona = 'SR-002',
    fiora = 'SR-003',
    ritsuki = 'SR-004',
    minayomi = 'SR-005',
    shizuka = 'SR-006',
    juneau = 'SR-007',
    britney = 'SR-008',
    nafrala = 'SR-009',
    tyrella = 'SR-010',
    teresa = 'SR-011',
    pulicia = 'SR-012',
    janelle = 'SR-013',
    tanocia = 'SR-014',
    yingying = 'SR-015',    
    baal = 'SSR-001',
    satan = 'SSR-002',
    iblis = 'SSR-003',
    salucia = 'SSR-004',
    lana = 'SSR-005',
    lulu = 'SSR-006',
    f_baal = 'SSR-007',
    i_iblis = 'SSR-008',
    noel = 'SSR-009',
    ks8 = 'SSR-010',
    mesmiia = 'SSR-011',
    e_satan = 'SSR-012',
    chizuru = 'SSR-013',
    daphne = 'SSR-014',
    s_shizuka = 'SSR-015',
    s_lulu = 'SSR-016',
    s_ks8 = 'SSR-017',
    s_nana = 'SSR-018',
    milae = 'SSR-019',
    asida = 'SSR-020',
    asina = 'SSR-021',
    aridya = 'SSR-022',
    lotiya = 'SSR-023',
    fufu = 'SSR-024',
    hm_fiora = 'SSR-025',
    karina = 'SSR-026',
    ibuki = 'SSR-027',
    h_britney = 'SSR-028',
    h_salucia = 'SSR-029',
    inori = 'SSR-030',
    sakuya = 'SSR-031',
    x_aiko = 'SSR-032',
    x_lana = 'SSR-033',
    evie = 'SSR-034',
    tm_minayomi = 'SSR-035',
    tm_ritsuki = 'SSR-036',
    b_baal = 'SSR-037',
    b_iblis = 'SSR-038',
    b_satan = 'SSR-039',
    miru = 'SSR-040',
    uruta = 'SSR-041',
    ayane = 'SSR-042',
    muila = 'SSR-043',
    f_caesar = 'SSR-044',
    w_chizuru = 'SSR-045',
    w_lulu = 'SSR-046',
    faya = 'SSR-047',
    usagihime = 'SSR-048',
    s_iblis = 'SSR-049',
    s_milae = 'SSR-050',
    s_noel = 'SSR-051',
    s_aridya = 'SSR-052',
    ichika = 'SSR-053',
    kana = 'SSR-054',
    q_asida = 'SSR-055',
    q_asina = 'SSR-056',
    emily = 'SSR-057',
    anjelica = 'SSR-058',
    c1_nana = 'SSR-059',
    geneva = 'SSR-060',
    lotus = 'SSR-061',
    didi = 'SSR-062',
    h_leona = 'SSR-063',
    h_lotiya = 'SSR-064',
    sherana = 'SSR-065',
    elizabeth = 'SSR-066',
    xx_aiko = 'SSR-067',
    x_shizuka = 'SSR-068',
    shiro = 'SSR-069',
    ny_salucia = 'SSR-070',
    ny_lana = 'SSR-071',
    v_baal = 'SSR-072',
    v_iblis = 'SSR-073',
    v_satan = 'SSR-074',
    lillane = 'SSR-075',
    c_lulu = 'SSR-076',
    m_juneau = 'SSR-077',
    m_britney = 'SSR-078',
    momo = 'SSR-079',
    n_caesar = 'SSR-080',
    d_irene = 'SSR-081',
    s_ayane = 'SSR-082',
    s_baal = 'SSR-083',
    s_fiora = 'SSR-084',
    s_aiko = 'SSR-085',
    o_lana = 'SSR-086',
    o_nana = 'SSR-087',
    sasha = 'SSR-088',
    bayliss = 'SSR-089',
    a_usagihime = 'SSR-090',
    d_miru = 'SSR-091',
    nyoro = 'SSR-092',
    h_ayane = 'SSR-093',
    h_shiro = 'SSR-094',
    inase = 'SSR-095',
    cartilla = 'SSR-096',
    x_aridya = 'SSR-097',
    x_iblis = 'SSR-098',
    w_evie = 'SSR-099',
    salina = 'SSR-100',
    noma = 'SSR-101',
    belladonna = 'SSR-102',
    nanami = 'SSR-103',
    w_noel = 'SSR-104',
    w_mesmiia = 'SSR-105',
    angelina = 'SSR-106',
    w_lillane = 'SSR-107',
    p_lulu = 'SSR-108',
    p_tyrella = 'SSR-109',
    lelya = 'SSR-110',
    a_nana = 'SSR-111',
    s_chizuru = 'SSR-112',
    s_salucia = 'SSR-113',
    s_caesar = 'SSR-114',
    s_satan = 'SSR-115',
    d_minayomi = 'SSR-116',
    oniyoiki = 'SSR-117',
    beer_shizuka = 'SSR-118',
    tsubaki = 'SSR-119',
    amethystina = 'SSR-120',
    bg_ayane = 'SSR-121',
    bg_iblis = 'SSR-122',
    susan = 'SSR-123',
    h_satan = 'SSR-124',
    m_nanami = 'SSR-125',
    m_ks8 = 'SSR-126',
    x_baal = 'SSR-127',
    x_muila = 'SSR-128',
    x_britney = 'SSR-129',
    x_ichika = 'SSR-130',
    ny_fiora = 'SSR-131',
    zaskia = 'SSR-132',
    p_aiko = 'SSR-133',
    ni_caesar = 'SSR-134',
    f_kana = 'SSR-135',
    star_mia = 'SSR-136',
    star_annee = 'SSR-137',
    bedard = 'SSR-138',
    c_noel = 'SSR-139',
    eunice = 'SSR-140',
    momDaphne = 'SSR-141',
    w_tsubaki = 'SSR-142',
    ss_iblis = 'SSR-143',
    s_evie = 'SSR-144',
    s_noma = 'SSR-145',
    forneusa = 'SSR-146',
    bu_ayane = 'SSR-147',
    sky_nanami = 'SSR-148',
    sky_baal = 'SSR-149',
}