export enum Locale {
    zh = 'zh',
    cn = 'cn',
    en = 'en',
    jp = 'jp',
    ko = 'ko',
}

export enum ErrorCode{
    PAGE_NOT_FOUND = 404,
    UNKNOWN_ERROR = 500,
    CANNOT_FIND_CHARACTER = 801,
}

export enum ErrorMessage{
    PAGE_NOT_FOUND = 'PAGE_NOT_FOUND',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    CANNOT_FIND_CHARACTER = 'CANNOT_FIND_CHARACTER',
}

export enum Element {
    FIRE = 'FIRE',
    WATER = 'WATER',
    WIND = 'WIND',
    LIGHT = 'LIGHT',
    DARK = 'DARK',
}

export enum Position {
    ATTACKER = 'ATTACKER',
    OBSTRUCTER = 'OBSTRUCTER',
    PROTECTOR = 'PROTECTOR',
    HEALER = 'HEALER',
    SUPPORTER = 'SUPPORTER',
}

export enum Rarity {
    SSR = 'SSR',
    SR = 'SR',
    R = 'R',
    N = 'N',
}

export enum SkillType {
    BASE_STAT = 'BASE_STAT',
    SKILL_S = 'SKILL_S',
    SKILL_1 = 'SKILL_1',
    SKILL_2 = 'SKILL_2',
    SKILL_3 = 'SKILL_3',
    SKILL_4 = 'SKILL_4',
    SKILL_5 = 'SKILL_5',
    ATTACK = 'ATTACK',
    LEADER = 'LEADER',
    PASSIVE_1 = 'PASSIVE_1',
    PASSIVE_2 = 'PASSIVE_2',
    PASSIVE_3 = 'PASSIVE_3',
    GENERAL_1 = 'GENERAL_1',
    GENERAL_2 = 'GENERAL_2',
    DISPATCH = 'DISPATCH',
}

export enum SkillTypeColor {
    BASE_STAT = '#925be6',
    SKILL_S = '#f0b023',
    SKILL_1 = '#f0b023',
    SKILL_2 = '#f0b023',
    SKILL_3 = '#f0b023',
    SKILL_4 = '#f0b023',
    SKILL_5 = '#f0b023',
    ATTACK = '#c60244',
    LEADER = '#085bad',
    PASSIVE_1 = '#43be57',
    PASSIVE_2 = '#43be57',
    PASSIVE_3 = '#43be57',
    GENERAL_1 = '#e591ea',
    GENERAL_2 = '#e591ea',
    DISPATCH = '#e591ea',
}

export enum LiberationStage {
    LIBERATION_0 = 'LIBERATION_0',
    LIBERATION_1 = 'LIBERATION_1',
    LIBERATION_2 = 'LIBERATION_2',
    LIBERATION_3 = 'LIBERATION_3',
}

export enum TagType {
    ELEMENT = 'ELEMENT',
    POSITION = 'POSITION',
    SPECIES = 'SPECIES',
    BODY = 'BODY',
    BREAST = 'BREAST',
    CLASS = 'CLASS',
    OTHER = 'OTHER',
}

export enum PotentialType {
    ATTACK = 'ATTACK',
    DEFENCE = 'DEFENCE',
    BALANCE = 'BALANCE',
    NR = 'NR',
}

export enum PotentialBuffType {
    ATK = 'ATK',
    HP = 'HP',
    PASSIVE = 'PASSIVE',
}

export enum ItemType {
    GENERAL = 'GENERAL',
    EVOLVE = 'EVOLVE',
    POTENTIAL = 'POTENTIAL',
    POTENTIAL_ADVANCED = 'POTENTIAL_ADVANCED',
    DISCIPLINE = 'DISCIPLINE',
}

export enum ItemCode {
    SLIVER_COIN = 'SLIVER_COIN',
    NAMELESS = 'NAMELESS',
    LIBERATE_STONE = 'LIBERATE_STONE',
    FLAWLESS = 'FLAWLESS',
    SKILL_FRAGMENT = 'SKILL_FRAGMENT',
    SKILL_STONE = 'SKILL_STONE',
    EVOLVE_FIRE_LV1 = 'EVOLVE_FIRE_LV1',
    EVOLVE_FIRE_LV2 = 'EVOLVE_FIRE_LV2',
    EVOLVE_FIRE_LV3 = 'EVOLVE_FIRE_LV3',
    EVOLVE_FIRE_LV4 = 'EVOLVE_FIRE_LV4',
    EVOLVE_WATER_LV1 = 'EVOLVE_WATER_LV1',
    EVOLVE_WATER_LV2 = 'EVOLVE_WATER_LV2',
    EVOLVE_WATER_LV3 = 'EVOLVE_WATER_LV3',
    EVOLVE_WATER_LV4 = 'EVOLVE_WATER_LV4',
    EVOLVE_WIND_LV1 = 'EVOLVE_WIND_LV1',
    EVOLVE_WIND_LV2 = 'EVOLVE_WIND_LV2',
    EVOLVE_WIND_LV3 = 'EVOLVE_WIND_LV3',
    EVOLVE_WIND_LV4 = 'EVOLVE_WIND_LV4',
    EVOLVE_LIGHT_LV1 = 'EVOLVE_LIGHT_LV1',
    EVOLVE_LIGHT_LV2 = 'EVOLVE_LIGHT_LV2',
    EVOLVE_LIGHT_LV3 = 'EVOLVE_LIGHT_LV3',
    EVOLVE_LIGHT_LV4 = 'EVOLVE_LIGHT_LV4',
    EVOLVE_DARK_LV1 = 'EVOLVE_DARK_LV1',
    EVOLVE_DARK_LV2 = 'EVOLVE_DARK_LV2',
    EVOLVE_DARK_LV3 = 'EVOLVE_DARK_LV3',
    EVOLVE_DARK_LV4 = 'EVOLVE_DARK_LV4',
    CLAW_LV1 = 'CLAW_LV1',
    CLAW_LV2 = 'CLAW_LV2',
    CLAW_LV3 = 'CLAW_LV3',
    IRON_LV1 = 'IRON_LV1',
    IRON_LV2 = 'IRON_LV2',
    IRON_LV3 = 'IRON_LV3',
    WATER_LV1 = 'WATER_LV1',
    WATER_LV2 = 'WATER_LV2',
    WATER_LV3 = 'WATER_LV3',
    MIXTURE_LV1 = 'MIXTURE_LV1',
    MIXTURE_LV2 = 'MIXTURE_LV2',
    MIXTURE_LV3 = 'MIXTURE_LV3',
    DUST_LV1 = 'DUST_LV1',
    DUST_LV2 = 'DUST_LV2',
    DUST_LV3 = 'DUST_LV3',
    HORN_LV1 = 'HORN_LV1',
    HORN_LV2 = 'HORN_LV2',
    SLIVER_LV1 = 'SLIVER_LV1',
    SLIVER_LV2 = 'SLIVER_LV2',
    OIL_LV1 = 'OIL_LV1',
    OIL_LV2 = 'OIL_LV2',
    CRYSTAL_LV1 = 'CRYSTAL_LV1',
    CRYSTAL_LV2 = 'CRYSTAL_LV2',
    FANG_LV1 = 'FANG_LV1',
    FANG_LV2 = 'FANG_LV2',
    BEAK_LV1 = 'BEAK_LV1',
    BEAK_LV2 = 'BEAK_LV2',
    SKIN_LV1 = 'SKIN_LV1',
    SKIN_LV2 = 'SKIN_LV2',
    BOOK_LV1 = 'BOOK_LV1',
    BOOK_LV2 = 'BOOK_LV2',
    FEATHER_LV1 = 'FEATHER_LV1',
    FEATHER_LV2 = 'FEATHER_LV2',
    WEB_LV1 = 'WEB_LV1',
    WEB_LV2 = 'WEB_LV2',
    DISCIPLINE_FIRE_LV1 = 'DISCIPLINE_FIRE_LV1',
    DISCIPLINE_FIRE_LV2 = 'DISCIPLINE_FIRE_LV2',
    DISCIPLINE_FIRE_LV3 = 'DISCIPLINE_FIRE_LV3',
    DISCIPLINE_WATER_LV1 = 'DISCIPLINE_WATER_LV1',
    DISCIPLINE_WATER_LV2 = 'DISCIPLINE_WATER_LV2',
    DISCIPLINE_WATER_LV3 = 'DISCIPLINE_WATER_LV3',
    DISCIPLINE_WIND_LV1 = 'DISCIPLINE_WIND_LV1',
    DISCIPLINE_WIND_LV2 = 'DISCIPLINE_WIND_LV2',
    DISCIPLINE_WIND_LV3 = 'DISCIPLINE_WIND_LV3',
    DISCIPLINE_LIGHT_LV1 = 'DISCIPLINE_LIGHT_LV1',
    DISCIPLINE_LIGHT_LV2 = 'DISCIPLINE_LIGHT_LV2',
    DISCIPLINE_LIGHT_LV3 = 'DISCIPLINE_LIGHT_LV3',
    DISCIPLINE_DARK_LV1 = 'DISCIPLINE_DARK_LV1',
    DISCIPLINE_DARK_LV2 = 'DISCIPLINE_DARK_LV2',
    DISCIPLINE_DARK_LV3 = 'DISCIPLINE_DARK_LV3',
    DISCIPLINE_FRUIT = 'DISCIPLINE_FRUIT',
}

export enum DispatchType {
    CAESAR_ROOM = 'CAESAR_ROOM',
    DUNGEON = 'DUNGEON',
    TRAINING_CENTER = 'TRAINING_CENTER',
    TREASURE_ROOM = 'TREASURE_ROOM',
    SEALED_CHAMBER = 'SEALED_CHAMBER',
}

export enum PuzzleType {
    EVENT = 'EVENT',
    HUMAN = 'HUMAN',
    DEMON = 'DEMON',
    SKY = 'SKY',
}

export enum PuzzleCode {
    EVENT_2021_SUMMER_1 = 'EVENT_2021_SUMMER_1',
    EVENT_2021_SUMMER_1_DMM = 'EVENT_2021_SUMMER_1_DMM',
    EVENT_2021_SUMMER_2 = 'EVENT_2021_SUMMER_2',
    EVENT_2021_SUMMER_3 = 'EVENT_2021_SUMMER_3',
    EVENT_2021_SUMMER_4 = 'EVENT_2021_SUMMER_4',
    EVENT_2021_XMAS_1 = 'EVENT_2021_XMAS_1',
    EVENT_2021_XMAS_2 = 'EVENT_2021_XMAS_2',
    EVENT_2022_SUMMER_1 = 'EVENT_2022_SUMMER_1',
    EVENT_2022_SUMMER_2 = 'EVENT_2022_SUMMER_2',
    EVENT_2022_SUMMER_3 = 'EVENT_2022_SUMMER_3',
    EVENT_2022_SUMMER_4 = 'EVENT_2022_SUMMER_4',
    EVENT_2022_XMAS_1 = 'EVENT_2022_XMAS_1',
    EVENT_2023_CNY_1 = 'EVENT_2023_CNY_1',
    EVENT_2023_SUMMER_1 = 'EVENT_2023_SUMMER_1',
    EVENT_2023_SUMMER_2 = 'EVENT_2023_SUMMER_2',
    EVENT_2023_SUMMER_3 = 'EVENT_2023_SUMMER_3',
    EVENT_2023_SUMMER_4 = 'EVENT_2023_SUMMER_4',
    EVENT_2023_XMAS_1 = 'EVENT_2023_XMAS_1',
    EVENT_2023_XMAS_2 = 'EVENT_2023_XMAS_2',
    EVENT_2024_SUMMER_1 = 'EVENT_2024_SUMMER_1',
    EVENT_2024_SUMMER_2 = 'EVENT_2024_SUMMER_2',
    EVENT_2024_SUMMER_3 = 'EVENT_2024_SUMMER_3',
    EVENT_2024_SUMMER_4 = 'EVENT_2024_SUMMER_4',
    HUMAN_SARIA = 'HUMAN_SARIA',
    HUMAN_PETRA = 'HUMAN_PETRA',
    HUMAN_KIKYOU = 'HUMAN_KIKYOU',
    HUMAN_KAEDE = 'HUMAN_KAEDE',
    HUMAN_OLA = 'HUMAN_OLA',
    HUMAN_KANI = 'HUMAN_KANI',
    HUMAN_CHARLENE = 'HUMAN_CHARLENE',
    HUMAN_MARTINA = 'HUMAN_MARTINA',
    HUMAN_CLARIE = 'HUMAN_CLARIE',
    HUMAN_ANNA = 'HUMAN_ANNA',
    HUMAN_BLAIRE = 'HUMAN_BLAIRE',
    HUMAN_NATASHA = 'HUMAN_NATASHA',
    DEMON_FLAY = 'DEMON_FLAY',
    DEMON_MANUELLA = 'DEMON_MANUELLA',
    DEMON_LORI = 'DEMON_LORI',
    DEMON_MINNOW = 'DEMON_MINNOW',
    DEMON_LAMIA = 'DEMON_LAMIA',
    DEMON_HARPY = 'DEMON_HARPY',
    DEMON_STEED = 'DEMON_STEED',
    DEMON_MUMU = 'DEMON_MUMU',
    SKY_PUNISHMENT = 'SKY_PUNISHMENT',
    SKY_BLISS = 'SKY_BLISS',
}

export enum UnitID {
    baal = '10001',
    satan = '10002',
    iblis = '10003',
    nana = '10802',
}